#!/usr/bin/env python3
"""生成清洗后的题库 — 每科每题型约55题"""
import json

def choice(id_base, text, opts, ans):
    return {"id":id_base,"type":"choice","text":text,"options":opts,"answer":ans}

def tf(id_base, text, ans):
    return {"id":id_base,"type":"tf","text":text,"answer":ans}

def fill(id_base, text):
    return {"id":id_base,"type":"fill","text":text}

# ============================================================
# 传感器技术 — 55 选择 + 55 判断 + 55 填空 = 165
# ============================================================
sensor_c = []
sensor_c.append(choice(1,"传感器的组成中起感知作用的部分是（　）",["弹性元件","敏感元件","转换元件","测量电路"],1))
sensor_c.append(choice(2,"以下哪项不是传感器的静态特性指标？（　）",["灵敏度","线性度","频响特性","迟滞"],2))
sensor_c.append(choice(3,"传感器将非电量转换为电量的核心部件是（　）",["电源","敏感元件","转换元件","外壳"],2))
sensor_c.append(choice(4,"下列属于电阻式传感器的是（　）",["热电偶","应变片","光电池","霍尔元件"],1))
sensor_c.append(choice(5,"应变片测力是基于哪种效应？（　）",["压电效应","应变效应","霍尔效应","光电效应"],1))
sensor_c.append(choice(6,"电桥测量电路的主要作用是（　）",["放大信号","将参数变化转为电压输出","滤波","整流"],1))
sensor_c.append(choice(7,"压电式传感器基于什么原理工作？（　）",["应变效应","压电效应","热电效应","光电效应"],1))
sensor_c.append(choice(8,"热电偶温度传感器的工作原理是（　）",["压电效应","热电效应","光电效应","霍尔效应"],1))
sensor_c.append(choice(9,"LM35 温度传感器的灵敏度是（　）",["5mV/℃","10mV/℃","15mV/℃","20mV/℃"],1))
sensor_c.append(choice(10,"以下属于接触式测温的传感器是（　）",["红外传感器","热电偶","光学高温计","辐射温度计"],1))
sensor_c.append(choice(11,"光栅式位移传感器利用了什么现象？（　）",["干涉","衍射","莫尔条纹","反射"],2))
sensor_c.append(choice(12,"超声波测距主要利用了超声波的什么特性？（　）",["穿透性","反射性","直进性","衰减性"],1))
sensor_c.append(choice(13,"电涡流传感器只能用于检测（　）",["绝缘体","半导体","金属导体","液体"],2))
sensor_c.append(choice(14,"光敏电阻的阻值随光照强度增强而（　）",["增大","减小","不变","不确定"],1))
sensor_c.append(choice(15,"RFID 的中文名称是（　）",["条码识别","射频识别","光学识别","声学识别"],1))
sensor_c.append(choice(16,"增量编码器的 A、B 两路脉冲相位差为（　）",["0°","45°","90°","180°"],2))
sensor_c.append(choice(17,"电容式传感器可用来测量（　）",["位移","温度","光照","磁场"],0))
sensor_c.append(choice(18,"霍尔式传感器基于什么效应工作？（　）",["压电效应","热电效应","霍尔效应","光电效应"],2))
sensor_c.append(choice(19,"CCD 的中文含义是（　）",["互补金属氧化物半导体","电荷耦合器件","图像处理器","光电倍增管"],1))
sensor_c.append(choice(20,"以下哪个不是物联网常用的传感器？（　）",["温度传感器","压力传感器","电动机","湿度传感器"],2))
sensor_c.append(choice(21,"传感器的线性度表示什么关系？（　）",["输入与输出之间的线性程度","灵敏度高低","响应速度","量程范围"],0))
sensor_c.append(choice(22,"迟滞指标反映传感器的什么特性？（　）",["正反行程不一致程度","零点漂移","温度稳定性","长期稳定性"],0))
sensor_c.append(choice(23,"下列哪个是传感器的动态特性指标？（　）",["灵敏度","线性度","响应时间","重复性"],2))
sensor_c.append(choice(24,"半导体应变片相比于金属应变片的主要优点是（　）",["成本低","灵敏度高","稳定性好","温度特性好"],1))
sensor_c.append(choice(25,"直流电桥的平衡条件是（　）",["R1R2=R3R4","R1R3=R2R4","R1R4=R2R3","R1=R2=R3=R4"],2))
sensor_c.append(choice(26,"压电材料的居里点是指（　）",["熔点","压电性消失的温度转变点","居里温度","烧结温度"],1))
sensor_c.append(choice(27,"下列不属于压电材料的是（　）",["石英晶体","压电陶瓷","PZT","纯铁"],3))
sensor_c.append(choice(28,"电感式传感器适宜测量的物理量是（　）",["温度","微小位移","光照强度","气体浓度"],1))
sensor_c.append(choice(29,"差动式电感传感器的优点不包括（　）",["灵敏度提高","线性度改善","温度补偿","量程增大"],3))
sensor_c.append(choice(30,"电容式传感器中，变介质型可用于测量（　）",["压力","液位","速度","加速度"],1))
sensor_c.append(choice(31,"热电阻传感器是利用金属导体的什么随温度变化？（　）",["电阻率","热导率","比热容","热膨胀系数"],0))
sensor_c.append(choice(32,"PTC 热敏电阻的特性是（　）",["温度升高电阻减小","温度升高电阻增大","电阻基本不变","电阻随机变化"],1))
sensor_c.append(choice(33,"K 型热电偶的正极是（　）",["铜","镍铬","镍硅","铂铑"],1))
sensor_c.append(choice(34,"热电偶的中间导体定律指出（　）",["可任意延长导线","可接入仪表不影响测量","必须使用补偿导线","不能用普通导线"],1))
sensor_c.append(choice(35,"热释电传感器基于什么效应？（　）",["压电效应","热电效应","铁电效应","热释电效应"],3))
sensor_c.append(choice(36,"光栅传感器中，莫尔条纹的作用不包括（　）",["放大位移","辨向","细分","测温"],3))
sensor_c.append(choice(37,"磁栅传感器利用什么原理？（　）",["电磁感应","磁电效应","磁阻效应","磁致伸缩"],0))
sensor_c.append(choice(38,"超声波在常温空气中的传播速度约为（　）",["340 m/s","500 m/s","700 m/s","1000 m/s"],0))
sensor_c.append(choice(39,"电涡流传感器的测量线圈通常采用什么结构？（　）",["螺线管","扁平线圈","环形线圈","多层线圈"],1))
sensor_c.append(choice(40,"光电池在电路中通常作为什么元件使用？（　）",["电压源","电流源","电阻","电容"],0))
sensor_c.append(choice(41,"光纤传感器按功能可分为哪两类？（　）",["传光型和传感型","单模和多模","玻璃和塑料","长距和短距"],0))
sensor_c.append(choice(42,"气敏传感器常用于检测什么？（　）",["温度","湿度","可燃气体浓度","光照"],2))
sensor_c.append(choice(43,"湿度传感器的感湿特征量通常是（　）",["电阻或电容","电压或电流","电感或阻抗","频率或相位"],0))
sensor_c.append(choice(44,"人的听觉频率范围约为（　）",["20Hz~20kHz","100Hz~10kHz","10Hz~100kHz","1kHz~20kHz"],0))
sensor_c.append(choice(45,"接近开关属于什么类型的传感器？（　）",["接触式","非接触式","光电式","压力式"],1))
sensor_c.append(choice(46,"电感式接近开关主要用于检测（　）",["金属物体","非金属物体","液体","气体"],0))
sensor_c.append(choice(47,"电容式物位传感器利用什么原理检测？（　）",["介电常数变化","电感变化","电阻变化","压力变化"],0))
sensor_c.append(choice(48,"测量转速常用的传感器是（　）",["温度传感器","接近开关或光电编码器","压力传感器","湿度传感器"],1))
sensor_c.append(choice(49,"光电编码器按输出信号分为（　）",["增量式和绝对式","模拟式和数字式","接触式和非接触式","线性式和旋转式"],0))
sensor_c.append(choice(50,"霍尔元件可以测量的物理量不包括（　）",["磁场","电流","电压","温度"],3))
sensor_c.append(choice(51,"条码技术中，EAN-13 是（　）",["一维条码","二维条码","三维条码","彩色条码"],0))
sensor_c.append(choice(52,"QR 码属于（　）",["一维条码","二维条码","堆叠条码","矩阵条码"],3))
sensor_c.append(choice(53,"RFID 系统的基本组成不包括（　）",["电子标签","读取器","天线","打印机"],3))
sensor_c.append(choice(54,"生物传感器中的生物功能膜起什么作用？（　）",["放大信号","识别被测物质","转换能量","滤波"],1))
sensor_c.append(choice(55,"图像识别系统中，图像采集的核心器件是（　）",["镜头","图像传感器","光源","处理器"],1))

sensor_t = []
sensor_t.append(tf(101,"传感器由敏感元件、转换元件和测量电路三部分组成。",True))
sensor_t.append(tf(102,"灵敏度越高的传感器，精度一定越高。",False))
sensor_t.append(tf(103,"电阻应变片分金属应变片和半导体应变片。",True))
sensor_t.append(tf(104,"压电传感器既适合静态也适合动态测量。",False))
sensor_t.append(tf(105,"热电偶必须使用补偿导线延长测量距离。",True))
sensor_t.append(tf(106,"阻值随温度升高而增大的热敏电阻是 NTC。",False))
sensor_t.append(tf(107,"超声波传感器既可发射也可接收超声波。",True))
sensor_t.append(tf(108,"电涡流传感器可检测任何材料物体。",False))
sensor_t.append(tf(109,"光敏二极管在电路中通常处于反向偏置。",True))
sensor_t.append(tf(110,"光纤传感器分为传光型和传感型两类。",True))
sensor_t.append(tf(111,"噪声的度量单位是分贝（dB）。",True))
sensor_t.append(tf(112,"绝对编码器断电后位置信息会丢失。",False))
sensor_t.append(tf(113,"RFID 标签分为有源和无源两类。",True))
sensor_t.append(tf(114,"生物传感器是在基础传感器上结合生物功能膜形成。",True))
sensor_t.append(tf(115,"指纹识别属于行为特征识别。",False))
sensor_t.append(tf(116,"CMOS 图像传感器成像质量一般优于 CCD。",False))
sensor_t.append(tf(117,"差动式电容传感器可减小非线性误差。",True))
sensor_t.append(tf(118,"电磁炉加热主要利用了涡流效应。",True))
sensor_t.append(tf(119,"传感器的量程越大，精度越高。",False))
sensor_t.append(tf(120,"电阻应变片必须进行温度补偿才能准确测量。",True))
sensor_t.append(tf(121,"直流电桥比交流电桥更适用于动态测量。",False))
sensor_t.append(tf(122,"压电式传感器属于发电型传感器。",True))
sensor_t.append(tf(123,"电感式传感器只能测量金属物体。",False))
sensor_t.append(tf(124,"变面积型电容传感器具有线性输出特性。",True))
sensor_t.append(tf(125,"热电偶可以测量很高的温度，上限可达数千摄氏度。",False))
sensor_t.append(tf(126,"铂热电阻 Pt100 在 0℃ 时电阻值为 100Ω。",True))
sensor_t.append(tf(127,"红外传感器不需要接触被测物体即可测温。",True))
sensor_t.append(tf(128,"超声波测距精度高于激光测距。",False))
sensor_t.append(tf(129,"电涡流传感器可以测量金属材料的厚度。",True))
sensor_t.append(tf(130,"光敏电阻的亮电阻远小于暗电阻。",True))
sensor_t.append(tf(131,"光纤传感器不受电磁干扰影响。",True))
sensor_t.append(tf(132,"气敏传感器的工作温度一般很高，需要加热。",True))
sensor_t.append(tf(133,"湿度传感器只能测量相对湿度。",False))
sensor_t.append(tf(134,"接近开关属于接触式传感器。",False))
sensor_t.append(tf(135,"电感式接近开关只能检测金属。",True))
sensor_t.append(tf(136,"电容式接近开关可以检测非金属物体。",True))
sensor_t.append(tf(137,"霍尔传感器可用来测量角度和转速。",True))
sensor_t.append(tf(138,"增量编码器有断电记忆功能。",False))
sensor_t.append(tf(139,"绝对编码器的精度比增量编码器低。",False))
sensor_t.append(tf(140,"一维条码只能存储数字信息。",False))
sensor_t.append(tf(141,"二维码比一维条码存储的信息量大。",True))
sensor_t.append(tf(142,"无源 RFID 标签需要读取器供电才能工作。",True))
sensor_t.append(tf(143,"生物传感器可用于环境监测。",True))
sensor_t.append(tf(144,"人脸识别属于生理特征识别。",True))
sensor_t.append(tf(145,"图像分辨率越高，文件越大。",True))
sensor_t.append(tf(146,"CCD 和 CMOS 都是图像传感器。",True))
sensor_t.append(tf(147,"光圈越大，进光量越少。",False))
sensor_t.append(tf(148,"传感器输出信号必须进行放大才能采集。",False))
sensor_t.append(tf(149,"电磁屏蔽是常用的抗干扰措施。",True))
sensor_t.append(tf(150,"传感器的标定就是用标准器具确定其性能参数。",True))
sensor_t.append(tf(151,"温度漂移是传感器的常见误差来源。",True))
sensor_t.append(tf(152,"A/D 转换器可将模拟信号转为数字信号。",True))
sensor_t.append(tf(153,"数字传感器的抗干扰能力一般优于模拟传感器。",True))
sensor_t.append(tf(154,"传感器在汽车电子中有广泛应用。",True))
sensor_t.append(tf(155,"所有传感器都需要外部电源供电才能工作。",False))

sensor_f = []
sensor_f.append(fill(201,"传感器是能感受规定的被测量并按照一定规律转换成______信号的器件或装置。"))
sensor_f.append(fill(202,"电阻应变片在实际应用中常用的温度补偿方法有应变补偿法和______补偿法。"))
sensor_f.append(fill(203,"压电材料受外力作用表面产生电荷的现象称为______效应。"))
sensor_f.append(fill(204,"热电偶回路中接入第三种导体，两端温度相同时不影响热电动势，这是______定律。"))
sensor_f.append(fill(205,"正温度系数热敏电阻的英文简写是______。"))
sensor_f.append(fill(206,"电感式传感器主要用于测量______等物理量。"))
sensor_f.append(fill(207,"电容式传感器分为变极距型、变面积型和______型三种。"))
sensor_f.append(fill(208,"光栅位移传感器通过测量______条纹移动实现精密测量。"))
sensor_f.append(fill(209,"人体正常体温 37℃ 对应的热力学温度为______K。（取整数）"))
sensor_f.append(fill(210,"气敏电阻内部通常含有用于加热的______电阻丝。"))
sensor_f.append(fill(211,"接近开关输出状态为 NO 时表示______触点。"))
sensor_f.append(fill(212,"压电传感器主要用于测量脉动、冲击、______等动态参数。"))
sensor_f.append(fill(213,"光电编码器按输出方式分为增量式和______式。"))
sensor_f.append(fill(214,"涡轮流量计利用______法测量流量。"))
sensor_f.append(fill(215,"与被测量无关的随机干扰信号称为______。"))
sensor_f.append(fill(216,"将模拟信号转换为数字信号的过程称为______转换。"))
sensor_f.append(fill(217,"金属热电阻传感器利用导体的______随温度变化来测温。"))
sensor_f.append(fill(218,"压电传感器中常用的压电材料有石英晶体和______陶瓷。"))
sensor_f.append(fill(219,"电桥电路中，当 R1×R4 = R2×R3 时，电桥处于______状态。"))
sensor_f.append(fill(220,"应变效应的物理本质是导体电阻率随______发生变化。"))
sensor_f.append(fill(221,"差动式传感器可以______灵敏度并改善线性度。"))
sensor_f.append(fill(222,"自感式传感器分为变气隙型、变面积型和______型。"))
sensor_f.append(fill(223,"铂热电阻 Pt100 在 100℃ 时的电阻值约为______Ω。"))
sensor_f.append(fill(224,"热电偶由两种______材料的导体在两端焊接而成。"))
sensor_f.append(fill(225,"热电偶的冷端补偿方法有补偿导线法和______法。"))
sensor_f.append(fill(226,"红外传感器按工作原理分为热型______型。"))
sensor_f.append(fill(227,"超声波传感器的核心元件是______换能器。"))
sensor_f.append(fill(228,"光敏三极管实质上是在______极管基础上加一个放大级。"))
sensor_f.append(fill(229,"光纤由纤芯、包层和______三层结构组成。"))
sensor_f.append(fill(230,"半导体气敏传感器利用其______随气体浓度的变化来检测。"))
sensor_f.append(fill(231,"电容式湿度传感器利用感湿材料的______随湿度变化。"))
sensor_f.append(fill(232,"噪声污染的三个要素是噪声源、传播途径和______。"))
sensor_f.append(fill(233,"电感式接近开关的______距离一般小于额定动作距离。"))
sensor_f.append(fill(234,"电容式物位传感器利用被测物的______常数不同测量。"))
sensor_f.append(fill(235,"霍尔元件在磁场中产生的______与磁感应强度成正比。"))
sensor_f.append(fill(236,"增量编码器每转输出的______数决定了其分辨率。"))
sensor_f.append(fill(237,"磁栅传感器由磁尺和______头两部分组成。"))
sensor_f.append(fill(238,"一维条码的编码方法主要有______和宽度调节法。"))
sensor_f.append(fill(239,"RFID 系统中读取器与标签之间通过______波通信。"))
sensor_f.append(fill(240,"EPC 的中文全称是______码。"))
sensor_f.append(fill(241,"生物传感器中的生物功能膜起______作用。"))
sensor_f.append(fill(242,"指纹识别利用的是指纹的______特征。"))
sensor_f.append(fill(243,"图像传感器分为 CCD 和______两大类。"))
sensor_f.append(fill(244,"数字图像的最小组成单元是______。"))
sensor_f.append(fill(245,"图像分辨率用每英寸______数（DPI）表示。"))
sensor_f.append(fill(246,"图像识别系统包括光源、镜头、相机、______系统和处理系统。"))
sensor_f.append(fill(247,"传感器输出信号的______处理包括滤波、放大、线性化等。"))
sensor_f.append(fill(248,"A/D 转换的采样率应满足______采样定理。"))
sensor_f.append(fill(249,"电磁屏蔽是用______材料来阻断电磁干扰。"))
sensor_f.append(fill(250,"传感器的标定分为静态标定和______标定两种。"))
sensor_f.append(fill(251,"温度漂移是指传感器输出随______变化的现象。"))
sensor_f.append(fill(252,"智能传感器内部通常集成了______处理器。"))
sensor_f.append(fill(253,"物联网感知层主要依靠______获取信息。"))
sensor_f.append(fill(254,"工业 4.0 中传感器的______化是实现智能制造的基础。"))
sensor_f.append(fill(255,"手机中使用的传感器包括加速度计、______传感器和光线传感器等。"))

# ============================================================
# 单片机技术 — 55 选择 + 55 判断 + 55 填空 = 165
# ============================================================
mcu_c = []
mcu_c.append(choice(1,"51 单片机的 CPU 主要由哪两部分组成？（　）",["运算器和控制器","存储器和运算器","控制器和存储器","输入输出接口"],0))
mcu_c.append(choice(2,"Intel 8051 是（　）位的单片机。",["4","8","16","32"],1))
mcu_c.append(choice(3,"程序计数器 PC 用于（　）",["存储数据","存储指令地址","计数脉冲","中断控制"],1))
mcu_c.append(choice(4,"单片机应用程序通常存放在（　）中。",["RAM","ROM","寄存器","I/O 口"],1))
mcu_c.append(choice(5,"51 单片机复位后 PC 的值为（　）",["0000H","0001H","0100H","FFFFH"],0))
mcu_c.append(choice(6,"ALE 引脚输出脉冲频率是晶振频率的（　）",["1/2","1/4","1/6","1/12"],2))
mcu_c.append(choice(7,"PSW 中 RS1 和 RS0 用于（　）",["选择工作寄存器组","设置波特率","控制中断","设置定时器模式"],0))
mcu_c.append(choice(8,"作为输入时需要外接上拉电阻的 I/O 口是（　）",["P0","P1","P2","P3"],0))
mcu_c.append(choice(9,"以下不是 51 单片机存储空间的是（　）",["片内 RAM","片内 ROM","扩展 RAM","显存"],3))
mcu_c.append(choice(10,"C51 中 unsigned char 类型长度为（　）",["1字节","2字节","4字节","8字节"],0))
mcu_c.append(choice(11,"while 循环中条件为（　）时结束。",["真","假","1","非0"],1))
mcu_c.append(choice(12,"LED 动态显示利用了（　）原理。",["光电效应","视觉暂留","电磁感应","压电效应"],1))
mcu_c.append(choice(13,"共阳极数码管显示\"0\"的段码是（　）",["0x3F","0xC0","0x06","0xF9"],1))
mcu_c.append(choice(14,"51 单片机定时器有（　）种工作方式。",["2","3","4","5"],2))
mcu_c.append(choice(15,"晶振 12MHz 时机器周期为（　）",["0.5μs","1μs","2μs","4μs"],1))
mcu_c.append(choice(16,"外部中断有（　）种触发方式。",["1","2","3","4"],1))
mcu_c.append(choice(17,"串行通信中数据速率指标是（　）",["波特率","频率","带宽","采样率"],0))
mcu_c.append(choice(18,"PC 与单片机通信常用（　）芯片做电平转换。",["MAX232","ADC0809","DAC0832","74HC573"],0))
mcu_c.append(choice(19,"定时器做计数器时计数脉冲来自（　）",["晶振","T0/T1 引脚","ALE","内部时钟"],1))
mcu_c.append(choice(20,"C51 中 code 关键字将数据存在（　）",["片内 RAM","程序存储器 ROM","片外 RAM","寄存器"],1))
mcu_c.append(choice(21,"51 单片机共有（　）个中断源。",["3","4","5","6"],2))
mcu_c.append(choice(22,"外部中断 0 的中断类型号是（　）",["0","1","2","3"],1))
mcu_c.append(choice(23,"定时器方式 1 是（　）位计数器。",["8","13","16","自动重装"],2))
mcu_c.append(choice(24,"串行口方式 0 的波特率是（　）",["固定","可调","可变","由 T1 决定"],0))
mcu_c.append(choice(25,"串行口发送中断标志 TI 由（　）清零。",["硬件自动","软件清零","自动","定时器清零"],1))
mcu_c.append(choice(26,"晶振频率 6MHz 时机器周期为（　）",["1μs","2μs","4μs","8μs"],1))
mcu_c.append(choice(27,"51 单片机外部 RAM 最多可扩展（　）字节。",["256","1K","64K","128K"],2))
mcu_c.append(choice(28,"P0 口作为地址总线时提供（　）",["高8位地址","低8位地址","数据","控制信号"],1))
mcu_c.append(choice(29,"P2 口作为地址总线时提供（　）",["高8位地址","低8位地址","数据","控制信号"],0))
mcu_c.append(choice(30,"MOVX 指令用于访问（　）",["片内 RAM","片外 RAM","ROM","SFR"],1))
mcu_c.append(choice(31,"51 单片机的堆栈位于（　）",["片内 RAM","片外 RAM","ROM","CPU"],0))
mcu_c.append(choice(32,"堆栈指针 SP 在复位后的初始值是（　）",["00H","07H","10H","FFH"],1))
mcu_c.append(choice(33,"下列哪个不是 C51 的数据类型？（　）",["int","float","string","char"],2))
mcu_c.append(choice(34,"C51 中 for 循环的循环体执行次数由（　）决定。",["条件判断","初始值","步长","三者共同"],0))
mcu_c.append(choice(35,"C51 中函数返回值的类型由（　）决定。",["函数名","函数声明","参数类型","返回值表达式"],1))
mcu_c.append(choice(36,"LED 共阴极数码管显示\"1\"的段码是（　）",["0x06","0x30","0x79","0x5B"],0))
mcu_c.append(choice(37,"数码管动态显示时，位选信号的作用是（　）",["选择显示数字","选择哪一位点亮","控制亮度","控制颜色"],1))
mcu_c.append(choice(38,"矩阵式键盘比独立式键盘（　）",["编程简单","占用 I/O 口少","响应快","成本高"],1))
mcu_c.append(choice(39,"按键消抖的常用方法不包括（　）",["软件延时","硬件滤波","增加按键数量","定时采样"],2))
mcu_c.append(choice(40,"共阳极数码管显示\"8\"的段码是（　）",["0x80","0x7F","0xC0","0x3F"],0))
mcu_c.append(choice(41,"TMOD 寄存器用于（　）",["控制中断优先级","设置定时器工作方式","控制串行口","设置电源模式"],1))
mcu_c.append(choice(42,"TCON 寄存器中 TR0 位的作用是（　）",["启动/停止 T0","标志 T0 溢出","外部中断触发","定时器中断标志"],0))
mcu_c.append(choice(43,"当定时器 T0 工作在方式 0 时，最大计数值是（　）",["256","8192","65536","128"],1))
mcu_c.append(choice(44,"EA=1 且 EX0=1 时，外部中断 0（　）",["被使能","被禁止","仅边沿触发","仅电平触发"],0))
mcu_c.append(choice(45,"中断服务程序的定义形式中，关键字 interrupt 后跟（　）",["中断类型号","优先级","使能位","中断向量"],0))
mcu_c.append(choice(46,"串行口 SCON 寄存器中 REN 位用于（　）",["允许接收","允许发送","设置波特率","设置工作方式"],0))
mcu_c.append(choice(47,"串行口方式 1 的帧格式包含（　）位数据。",["7","8","9","10"],1))
mcu_c.append(choice(48,"定时器 T1 做波特率发生器时常用工作方式（　）",["方式0","方式1","方式2","方式3"],2))
mcu_c.append(choice(49,"51 单片机串行口的发送引脚是（　）",["TXD","RXD","P3.0","P3.1"],0))
mcu_c.append(choice(50,"串行异步通信的起始位是（　）",["高电平","低电平","上升沿","下降沿"],1))
mcu_c.append(choice(51,"52 单片机比 51 单片机多出的资源是（　）",["定时器 T2","外部中断 2","串行口 1","A/D 转换器"],0))
mcu_c.append(choice(52,"看门狗定时器的作用是（　）",["计时","防止程序跑飞","产生中断","测量频率"],1))
mcu_c.append(choice(53,"单片机应用系统开发的第一步是（　）",["编写程序","设计电路","需求分析","焊接调试"],2))
mcu_c.append(choice(54,"在 Keil C51 中编译生成的 hex 文件是（　）",["汇编文件","目标文件","可执行文件","文本文件"],2))
mcu_c.append(choice(55,"51 单片机的RST 引脚复位电平是（　）",["高电平","低电平","脉冲","下降沿"],0))

mcu_t = []
mcu_t.append(tf(101,"单片机将 CPU、存储器和 I/O 接口集成在一块芯片上。",True))
mcu_t.append(tf(102,"51 单片机复位后所有 I/O 口引脚均为高电平。",True))
mcu_t.append(tf(103,"工作寄存器有 4 组，每组 8 个，共 32 个。",True))
mcu_t.append(tf(104,"51 单片机内部 RAM 地址范围是 00H~FFH。",False))
mcu_t.append(tf(105,"定时器方式 0 是 13 位定时/计数器。",True))
mcu_t.append(tf(106,"EA=0 时 CPU 响应所有中断请求。",False))
mcu_t.append(tf(107,"共阴极数码管显示需要送高电平段码。",True))
mcu_t.append(tf(108,"独立式按键适用于按键数量少的场合。",True))
mcu_t.append(tf(109,"机械按键按下时有抖动，需去抖处理。",True))
mcu_t.append(tf(110,"C 语言程序总是从 main 函数开始执行。",True))
mcu_t.append(tf(111,"LCD1602 只能显示字母和数字。",False))
mcu_t.append(tf(112,"串行口方式 0 的波特率固定。",True))
mcu_t.append(tf(113,"外部中断 0 的中断类型号为 0。",False))
mcu_t.append(tf(114,"定时器方式 2 是 8 位自动重装。",True))
mcu_t.append(tf(115,"do-while 循环至少执行一次循环体。",True))
mcu_t.append(tf(116,"P3 口具有第二功能。",True))
mcu_t.append(tf(117,"上拉电阻是为了提高输出电流能力。",True))
mcu_t.append(tf(118,"串行通信比并行通信速度快。",False))
mcu_t.append(tf(119,"51 单片机内部有 128 字节 RAM。",True))
mcu_t.append(tf(120,"特殊功能寄存器（SFR）分布在 80H~FFH 范围内。",True))
mcu_t.append(tf(121,"晶振频率越高，机器周期越短。",True))
mcu_t.append(tf(122,"单片机复位时所有 SFR 被清零。",False))
mcu_t.append(tf(123,"P0 口内部没有上拉电阻。",True))
mcu_t.append(tf(124,"C51 中的 bit 类型可定义位变量。",True))
mcu_t.append(tf(125,"sbit 用于定义特殊功能寄存器的可寻址位。",True))
mcu_t.append(tf(126,"数组下标从 1 开始计数。",False))
mcu_t.append(tf(127,"字符串以 '\\0' 作为结束符。",True))
mcu_t.append(tf(128,"C51 中 _nop_() 函数用于产生一个机器周期延时。",True))
mcu_t.append(tf(129,"数码管静态显示比动态显示占用 I/O 口少。",False))
mcu_t.append(tf(130,"矩阵键盘通常采用行扫描法识别按键。",True))
mcu_t.append(tf(131,"LED 的阳极接 VCC 时称为共阳极接法。",True))
mcu_t.append(tf(132,"定时器工作在计数方式时计数脉冲来自外部引脚。",True))
mcu_t.append(tf(133,"定时器溢出时 TF 位由软件清零。",False))
mcu_t.append(tf(134,"中断服务程序中必须清除中断标志。",False))
mcu_t.append(tf(135,"外部中断的电平触发方式需要低电平有效。",True))
mcu_t.append(tf(136,"中断优先级由 IP 寄存器设定。",True))
mcu_t.append(tf(137,"51 单片机有 6 个中断源。",False))
mcu_t.append(tf(138,"串行口发送完一帧数据后 TI 自动置 1。",True))
mcu_t.append(tf(139,"串行口接收完一帧数据后 RI 自动置 1。",True))
mcu_t.append(tf(140,"波特率表示每秒传输的字节数。",False))
mcu_t.append(tf(141,"RS-232 电平与 TTL 电平兼容。",False))
mcu_t.append(tf(142,"单片机应用系统设计必须包含硬件和软件两部分。",True))
mcu_t.append(tf(143,"Proteus 可用于单片机系统仿真。",True))
mcu_t.append(tf(144,"Keil C51 是汇编语言开发工具。",False))
mcu_t.append(tf(145,"hex 文件可用于烧录单片机。",True))
mcu_t.append(tf(146,"引脚分配是硬件设计的重要步骤。",True))
mcu_t.append(tf(147,"上电复位电路通常由电阻和电容组成。",True))
mcu_t.append(tf(148,"晶体振荡器两端应接匹配电容。",True))
mcu_t.append(tf(149,"程序调试时可以使用断点功能。",True))
mcu_t.append(tf(150,"I/O 口驱动 LED 时需加限流电阻。",True))
mcu_t.append(tf(151,"继电器驱动需要加续流二极管保护。",True))
mcu_t.append(tf(152,"光耦可用于电气隔离。",True))
mcu_t.append(tf(153,"PWM 波可用定时器产生。",True))
mcu_t.append(tf(154,"单片机系统功耗与工作频率成正比。",True))
mcu_t.append(tf(155,"所有单片机都可以用 C 语言编程。",True))

mcu_f = []
mcu_f.append(fill(201,"单片机应用系统由硬件系统和______系统两部分组成。"))
mcu_f.append(fill(202,"51 单片机的 XTAL1、XTAL2 引脚是______引脚。"))
mcu_f.append(fill(203,"单片机最小系统包括芯片、电源、______电路和复位电路。"))
mcu_f.append(fill(204,"复位信号需保持______个机器周期以上的高电平才有效。"))
mcu_f.append(fill(205,"P0 口做通用 I/O 输出时必须外接______电阻。"))
mcu_f.append(fill(206,"C51 中 data 存储类型表示变量在片内 RAM 的______区域。"))
mcu_f.append(fill(207,"内部 RAM 低 128 字节分为工作寄存器区、______区和用户 RAM 区。"))
mcu_f.append(fill(208,"51 单片机的中断系统由 IE、IP 和______等寄存器组成。"))
mcu_f.append(fill(209,"定时器启动后 TCON 中的______位被置 1。"))
mcu_f.append(fill(210,"SCON 中的 TI 位表示______标志。"))
mcu_f.append(fill(211,"51 单片机共有______个中断源。"))
mcu_f.append(fill(212,"LED 大屏幕显示通常采用______扫描方式。"))
mcu_f.append(fill(213,"键盘消抖常用的有硬件和______去抖两种方法。"))
mcu_f.append(fill(214,"扩展外部存储器时 P0 口分时做数据总线和______位地址总线。"))
mcu_f.append(fill(215,"串行异步通信的一帧包括起始位、数据位、______位和停止位。"))
mcu_f.append(fill(216,"C51 中指向片外 RAM 的指针应使用______存储类型。"))
mcu_f.append(fill(217,"单片机应用系统开发流程包括______、硬件设计、软件设计、联调和测试。"))
mcu_f.append(fill(218,"51 单片机的 PC 是一个______位计数器。"))
mcu_f.append(fill(219,"DPTR 是 51 单片机唯一的______位寄存器。"))
mcu_f.append(fill(220,"堆栈操作遵循______原则。"))
mcu_f.append(fill(221,"PSW 中的 CY 位是______标志位。"))
mcu_f.append(fill(222,"51 单片机共有______个并行 I/O 口。"))
mcu_f.append(fill(223,"中断响应的三个条件是：中断使能、中断请求和______。"))
mcu_f.append(fill(224,"定时器方式 0 是______位计数结构。"))
mcu_f.append(fill(225,"定时器方式 2 是______位自动重装计数结构。"))
mcu_f.append(fill(226,"外部中断 0 的入口地址是______H。"))
mcu_f.append(fill(227,"定时器 T0 的入口地址是______H。"))
mcu_f.append(fill(228,"串行口中断的入口地址是______H。"))
mcu_f.append(fill(229,"串行口方式 1 的波特率由______决定。"))
mcu_f.append(fill(230,"SBUF 是串行口的______寄存器。"))
mcu_f.append(fill(231,"共阳极数码管位选端接______电平有效。"))
mcu_f.append(fill(232,"LED 的工作电流通常为______mA 左右。"))
mcu_f.append(fill(233,"矩阵键盘的按键识别方法有行扫描法和______法。"))
mcu_f.append(fill(234,"液晶 1602 的 RS 引脚用于选择______或数据寄存器。"))
mcu_f.append(fill(235,"ADC0809 是______位逐次逼近型 A/D 转换器。"))
mcu_f.append(fill(236,"DAC0832 是 8 位______型 D/A 转换器。"))
mcu_f.append(fill(237,"晶振频率 12MHz 时一个机器周期为______μs。"))
mcu_f.append(fill(238,"晶振频率 6MHz 时一个机器周期为______μs。"))
mcu_f.append(fill(239,"定时器 50ms 定时（12MHz）的计数初值是______H。"))
mcu_f.append(fill(240,"C51 中 while 循环与 do-while 循环的主要区别是先执行______判断。"))
mcu_f.append(fill(241,"C51 中一维数组的声明格式为：类型 数组名[______]；"))
mcu_f.append(fill(242,"二维数组在内存中是按______顺序存储的。"))
mcu_f.append(fill(243,"sbit 用于定义______功能寄存器中的位。"))
mcu_f.append(fill(244,"C51 中 _crol_ 函数用于将数据循环______移。"))
mcu_f.append(fill(245,"unsigned int 类型的取值范围是 0 ~______。"))
mcu_f.append(fill(246,"串行通信按方向分为单工、半双工和______三种方式。"))
mcu_f.append(fill(247,"RS-232 逻辑 1 的电平范围是______V。"))
mcu_f.append(fill(248,"RS-485 采用______传输方式，抗干扰能力强。"))
mcu_f.append(fill(249,"I²C 总线由 SDA 和______两根线组成。"))
mcu_f.append(fill(250,"SPI 总线有 4 根信号线：MOSI、MISO、SCK 和______。"))
mcu_f.append(fill(251,"单片机程序下载方式有 ISP、______和并行编程等。"))
mcu_f.append(fill(252,"STC 单片机通常使用______软件下载程序。"))
mcu_f.append(fill(253,"STM32 是基于______内核的 32 位微控制器。"))
mcu_f.append(fill(254,"Arduino 的编程语言本质上是______语言。"))
mcu_f.append(fill(255,"物联网终端设备常采用______单片机以降低功耗。"))

# ============================================================
# 构建数据
# ============================================================
sensor_subject = {
    "name": "传感器技术",
    "icon": "📡",
    "dir": "思考练习",
    "total": 165,
    "pages": 24,
    "questions": sensor_c + sensor_t + sensor_f
}
mcu_subject = {
    "name": "单片机技术",
    "icon": "💻",
    "dir": "思考与练习题1",
    "total": 165,
    "pages": 15,
    "questions": mcu_c + mcu_t + mcu_f
}

SUBJECTS = [sensor_subject, mcu_subject]

js_content = "var SUBJECTS = " + json.dumps(SUBJECTS, ensure_ascii=False, indent=2) + ";\n"

with open("/Users/zzzzed/opencodes/electest/universal_review/scan/questions.js", "w", encoding="utf-8") as f:
    f.write(js_content)

sl = len(sensor_c); st = len(sensor_t); sf = len(sensor_f)
ml = len(mcu_c); mt = len(mcu_t); mf = len(mcu_f)
print(f"✓ 传感器: {sl+st+sf} 题（选择{sl} 判断{st} 填空{sf}）")
print(f"✓ 单片机: {ml+mt+mf} 题（选择{ml} 判断{mt} 填空{mf}）")
print(f"总计: {sl+st+sf+ml+mt+mf} 题")

# ============================================================
# 嵌入到 design_draft.html
# ============================================================
with open("/Users/zzzzed/opencodes/electest/universal_review/scan/design_draft.html", "r", encoding="utf-8") as f:
    html = f.read()

old_start = html.index("var SUBJECTS = [")
old_end = html.index("];", old_start) + 2
new_html = html[:old_start] + js_content.strip() + "\n" + html[old_end:]

import re
new_html = re.sub(r'sensorTotal">\d+</span> 题 · 24 页', 'sensorTotal">165</span> 题 · 24 页', new_html)
new_html = re.sub(r'mcuTotal">\d+</span> 题 · 15 页', 'mcuTotal">165</span> 题 · 15 页', new_html)
new_html = re.sub(r'0/\d+ 题\' %\n?\'', '0/165 题', new_html)
new_html = new_html.replace('0/288 题', '0/165 题')
new_html = new_html.replace('0/288 题', '0/165 题')
new_html = re.sub(r'style="color:#2563eb">\d+</div>', 'style="color:#2563eb">165</div>', new_html)
new_html = re.sub(r'style="color:#7c3aed">\d+</div>', 'style="color:#7c3aed">330</div>', new_html)

with open("/Users/zzzzed/opencodes/electest/universal_review/scan/design_draft.html", "w", encoding="utf-8") as f:
    f.write(new_html)

print("✓ design_draft.html 已更新")
